// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Hỗ trợ API",
            "email": "support@nongsan.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Trả về danh sách tất cả người dùng trong hệ thống\nKết quả trả về bao gồm thông tin cơ bản của người dùng và trạng thái hoạt động",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lấy danh sách người dùng",
                "responses": {
                    "200": {
                        "description": "Danh sách người dùng",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "users": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/entity.User"
                                    }
                                }
                            }
                        },
                        "examples": {
                            "application/json": {
									"users": [
										{
											"id": 3,
											"name": "VietHa",
											"email": "hanguyenthua07@gmail.com",
											"password": "123456",
											"is_active": true,
											"created_at": "2025-04-04T11:01:13.928+07:00",
											"updated_at": "2025-04-07T16:09:40.278+07:00",
											"Roles": [
												{
													"id": 1,
													"name": "ROLE_ADMIN",
													"created_at": "2025-04-03T23:03:29+07:00",
													"updated_at": "2025-04-03T23:03:31+07:00",
													"permissions": null
												},
												{
													"id": 2,
													"name": "ROLE_USER",
													"created_at": "2025-04-03T23:03:33+07:00",
													"updated_at": "2025-04-03T23:03:34+07:00",
													"permissions": null
												},
												{
													"id": 3,
													"name": "ROLE_EMPLOYEE",
													"created_at": "2025-04-03T23:03:35+07:00",
													"updated_at": "2025-04-03T23:03:36+07:00",
													"permissions": null
												}
											],
											"Tokens": null,
											"Permissions": null
										},
										{
											"id": 4,
											"name": "Nguyen Van A",
											"email": "nguyenvana@example.com",
											"password": "123456",
											"is_active": true,
											"created_at": "2025-04-06T22:46:17.735+07:00",
											"updated_at": "2025-04-06T22:46:17.735+07:00",
											"Roles": [
												{
													"id": 1,
													"name": "ROLE_ADMIN",
													"created_at": "2025-04-03T23:03:29+07:00",
													"updated_at": "2025-04-03T23:03:31+07:00",
													"permissions": null
												}
											],
											"Tokens": null,
											"Permissions": null
										},
										{
											"id": 6,
											"name": "Nguyen Van B",
											"email": "nguyenvana@example.com",
											"password": "123456",
											"is_active": true,
											"created_at": "2025-04-06T22:51:51.781+07:00",
											"updated_at": "2025-04-06T22:51:51.781+07:00",
											"Roles": [
												{
													"id": 1,
													"name": "ROLE_ADMIN",
													"created_at": "2025-04-03T23:03:29+07:00",
													"updated_at": "2025-04-03T23:03:31+07:00",
													"permissions": null
												}
											],
											"Tokens": null,
											"Permissions": null
										}
									]
								}
                        }
                    },
                    "500": {
                        "description": "Lỗi hệ thống",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        },
                        "examples": {
                            "application/json": {
                                "error": "Không thể kết nối đến cơ sở dữ liệu"
                            }
                        }
                    }
                }
            }
        }
    },
		"/user": {
		  "get": {
			"summary": "Lấy thông tin người dùng theo ID",
			"tags": ["users"],
			"parameters": [{
			  "name": "id",
			  "in": "path",
			  "required": true,
			  "type": "integer"
			}],
			"responses": {
			  "200": {
				"description": "Thông tin người dùng",
				"schema": { "$ref": "#/definitions/entity.User" }
			  },
			  "404": {
				"description": "Không tìm thấy người dùng"
			  }
			}
		  }
		},
    "definitions": {
        "entity.Permissions": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "read"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Xem danh sách người dùng"
                },
                "resource": {
                    "type": "string",
                    "example": "users"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "entity.Roles": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Quản trị viên"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Permissions"
                    }
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "entity.Tokens": {
            "type": "object",
            "properties": {
                "access_token_expires_at": {
                    "type": "string",
                    "example": "2023-01-01T01:00:00Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "refresh_token": {
                    "type": "string",
                    "example": "abcdef123456"
                },
                "refresh_token_expires_at": {
                    "type": "string",
                    "example": "2023-01-08T00:00:00Z"
                },
                "token": {
                    "type": "string",
                    "example": "xyz123"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Nguyễn Văn A"
                },
                "password": {
                    "type": "string",
                    "example": "hashedpassword123"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Permissions"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Roles"
                    }
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Tokens"
                    }
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2004",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Nông sản API",
	Description:      "API cho hệ thống bán hàng nông sản trực tuyến",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
